name: Build and Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18.14.0"

            - name: Setup nbconvert
              run: pip install nbconvert

            - name: Convert notebooks
              run: bash ./convert.sh

            - name: Setup dependencies
              working-directory: ./.docs
              run: npm ci

            - name: Build docs
              working-directory: ./.docs
              run: npm run build

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: production-files
                  path: ./.docs/build

    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: production-files
                  path: ./.docs/build

            - name: Deploy on GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: gh-pages
                  publish_dir: ./.docs/build
